### ISSUE TITLE
Split package dependencies

### ISSUE THREAD

**Issue by Sinclert** [diana-hep/madminer#429]
This issue aims to proposed a new way of installing the package dependencies.

---

### Current situation
Madminer currently installs all the dependencies specified in its [setup.py](https://github.com/diana-hep/madminer/blob/master/setup.py) every time a user runs:
```shell script
pip install madminer
```

---

### Issue
For most of the times, end user would be interested in using madminer as a Python package for their own computations and goals. Therefore, only a subset of the originally defined dependencies would be needed.

I have identified the following scenarios:

- **Core dependencies:** the ones being used in the [madminer](https://github.com/diana-hep/madminer/tree/master/madminer) folder:
    - `six`.
    - `numpy`.
    - `scipy`.
    - `h5py`.
    - `scikit-hep`.
    - `torch`.
    - `uproot`.
    - `matplotlib`.
- **Documentation dependencies:** those using in [docs](https://github.com/diana-hep/madminer/tree/master/docs) folder, directly or indirectly:
    - `numpydoc`.
    - `recommonmark`.
    - `sphinx`.
    - `sphinx_rtd_theme`.
- **Testing dependencies:** those used for tests.
    - `pytest`.
- **Examples dependencies:** those used in the [examples](https://github.com/diana-hep/madminer/tree/master/examples) folder, that are not in the core ones:
    - `bqplot`.
    - `pandas`.

---

### Proposal
My proposal is to start using the [setup.py](https://github.com/diana-hep/madminer/blob/master/setup.py) `extra_require` keyword argument, passing a dictionary listing the non-core dependencies as values of the scenario keys (_"docs"_, _"test"_ and _"examples"_).

After doing so, user could have thinner granularity over what Madminer dependencies are installed on their systems. Additionally, it will also be beneficial for reducing Docker image sizes some MBs.

Something to consider is that installing Madminer for developers would change from:
```shell script
pip install madminer
```

To:
```shell script
pip install madminer"[docs]"
# And / or
pip install madminer"[test]"
# And / or
pip install madminer"[examples]"
```

---

### Final comments:
- I have not listed `scikit-learn` as a dependency (even if it is declared at the [setup.py](https://github.com/diana-hep/madminer/blob/master/setup.py)) because I could not figure out where it is used within Madminer. Am I missing something here? @johannbrehmer .
- I think it would be beneficial to also include _"docs"_ dependencies into the _"test"_ ones, as testing documentation builds could be added in the future.

**Comment by johannbrehmer** [comment]
Hi,

This is a good idea, I'm on board. Your categorization looks good to me! Indeed, `scikit-learn` is indeed not needed (anymore), good catch.

Cheers,
Johann
