### ISSUE TITLE
Drop Python2 support

### ISSUE THREAD

**Issue by Sinclert** [diana-hep/madminer#437]
Is there a plan to drop Python2 support on the near future?

I am not referring to the `python2` commands that Madminer need to pass to sub-shells in order to interact with [_MadGraph_](https://launchpad.net/mg5amcnlo) (still on Python2), but to the client-side support of launch Madminer features using Python2 or Python3.

I think dropping support will open the window to:

1. Reduced Docker image.
2. Simplified code.

**Comment by Sinclert** [comment]
If there is no plan on this regard, I will start working on migrating the codebase to **Python3.6+**

The reason I think Python 3.6 is a good version to serve as _floor_ is that it introduced very nice features like:
- [F-strings](https://www.python.org/dev/peps/pep-0498/).
- [Faster and more compact dictionaries](https://www.youtube.com/watch?v=npw4s1QTmPg).
- [Native support for `pathlib` classes in built-ins](https://docs.python.org/3.6/library/pathlib.html).

**Comment by johannbrehmer** [comment]
Hi Sinclert,

thanks for the suggestion. I am on the fence here. I agree with you that Python 3.6 is the better Python.

At the same time, as far as I know, MadGraph regrettably still forces their users to have Python 2.6/2.7. For users that are not used to virtual environments and that run everything on the same setup, it may be easier to just have one Python 2.x installation and use that for both MadMiner and MadGraph. That's why I would vote for sticking to Python 2 support until MadGraph finally starts supporting Python 3.

I'm open to being convinced though.

Cheers,
Johann

**Comment by Sinclert** [comment]
I agree it is an annoying situation.

Although it is still a _beta_ product, it seems that MadGraph `3.X.X` is being developed to support Python 3 ([announcement](https://launchpad.net/mg5amcnlo/+announcement/22860)).

Something we could do is to migrate the codebase to **Python 3 exclusive** features in a new branch (called `python3-only`), targeting a specific version of MadMiner. `0.8.0`? `1.0.0`?

That way development can continue on the `0.7.X` version series, but we have a lighter and modern syntax alternative ready to be used whenever MadGraph developers decide to embrace 2020 technologies 😄 

Opinions? @johannbrehmer @KlingFelix @cranmer @irinaespejo

**Comment by johannbrehmer** [comment]
The separate branch solution sounds great, I'm definitely on board with that!

**Comment by Sinclert** [comment]
I have a _Python3.6+ only_ branch ready on [my forked repository](https://github.com/Sinclert/madminer/tree/drop-python-2).

I will create a PR with a detailed description of all the Python2 -> Python3 migration changes I did, including why and how I did them, once a `python3-only` branch is available on the main repo (I do not have permissions to create it).

**Comment by johannbrehmer** [comment]
Perfect! The `drop-python-2` branch now exists on the main repo, feel free to open a PR at any time.

Comparison: https://github.com/diana-hep/madminer/compare/drop-python-2...Sinclert:drop-python-2
