### ISSUE TITLE
Require Python 3.6+ in setup.py to avoid breaking future releases

### ISSUE THREAD

**Issue by matthewfeickert** [diana-hep/madminer#452]
`madminer` dropped Python 2 support in PR #438 (:tada: :rocket: :snake:), but there are some lingering remnants in the metadata of `setup.py` that can pose problems to future releases that can cause them to break. Specifically, 

https://github.com/diana-hep/madminer/blob/7fc053b23beca88429c0120b2b7d7b6c049944a9/setup.py#L33
https://github.com/diana-hep/madminer/blob/7fc053b23beca88429c0120b2b7d7b6c049944a9/setup.py#L114

still allows the latest releases of `madminer` to be installed on Python 2.7, but if Python 3 only syntax is ever used these releases will break. As the PyPI metadata indicates that `madminer` is Python 3.6+

https://github.com/diana-hep/madminer/blob/7fc053b23beca88429c0120b2b7d7b6c049944a9/setup.py#L129-L131

this should be reflected in the Python requires with

```python
REQUIRES_PYTHON = ">=3.6, <4" 
```

Though you might want to also think about dropping Python 3.6 support as [it will be EOL in December 2021](https://www.python.org/dev/peps/pep-0494/).

Dropping support should also mean dropping testing, so 

https://github.com/diana-hep/madminer/blob/7fc053b23beca88429c0120b2b7d7b6c049944a9/.travis.yml#L9-L11

should go.

I'm willing to open a PR for this and to also add new CI using GHA that makes it far nicer (IMO) than Travis.

**Comment by matthewfeickert** [comment]
@johannbrehmer there is overlap between this Issue and PR #442. Is a contributed PR helpful here, or are you going to take care of this all in your PR?

**Comment by Sinclert** [comment]
Hey @matthewfeickert , I read this issue coming from your [madminer-tutorial PR](https://github.com/cranmer/madminer-tutorial/pull/6).

Please note that my [_Drop Python2 support_](https://github.com/diana-hep/madminer/pull/438) PR (the one you mentioned), was merged from my fork, to the `python3-only` branch in this repository. **The changes you commented on are already done**, but they have not yet merged to the `master` branch.

Please, consider closing this issue, and continue conversation about the `python3-only` -> `master` merge [here](https://github.com/diana-hep/madminer/pull/442).

**Comment by matthewfeickert** [comment]
Resolved by https://github.com/diana-hep/madminer/pull/442/commits/23c59221c81f164a113267589a0df572f4a4df11 in PR #442
