### ISSUE TITLE
Python 2 → 3 conversion error 

### ISSUE THREAD

**Issue by sbrass** [diana-hep/madminer#459]
Dear all,

there is a mistake in _madminer/analysis/dataanalyzer.py_ after the transition from six ( 622d15f5a6119af3f8e14d301aafb0ea19a098a4):

    def _benchmark_array(self):
        return np.asarray([
            benchmark.values() for benchmark in self.benchmarks.values()
        ])

You use `benchmark.values()`, however, that gives an view object, and not the "actual" values.
You should wrap it in `list(benchmark.values())`; 
https://docs.python.org/3/library/stdtypes.html?highlight=dict#dictionary-view-objects.

Cheers,
Simon

**Comment by Sinclert** [comment]
Hi @sbrass ,

You are absolutely right. My understanding when migrating the codebase was that, as a numpy array was being built out of it, the code snippet fell into the _"Dictionary views can be iterated over to yield their respective data"_ description from the documentation.

Did you encounter any `v0.8.0`-specific errors on your existing experiments?

**Comment by sbrass** [comment]
> My understanding when migrating the codebase was that, as a numpy array was being built out of it, the code snippet fell into the "Dictionary views can be iterated over to yield their respective data" description from the documentation.

Yes, it iterates over the dict view, however, the dict view object returns an `odict` object, not a float. (That is really somehow ambiguous in the documentation.)

So far, I did not encounter any further issue, but I'll push any further issue here if I find one.
